version: '3.7'

services:
  textimager-database:
    image: mongo:4.2
    container_name: 'textimager-database'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'rootpassword'
    ports: 
      - '27017:27017'
    volumes: 
      - duccDB:/data/db
    networks:
      - exchange
  
  textimager-server:
    depends_on:
      - textimager-database
    build:
      context: ./ducc
      dockerfile: Dockerfile
    container_name: 'textimager-server'
    hostname: 'textimager-server-head'
    environment:
      TI_DOCKER_HEAD_HOST: 'textimager-server-head'
    restart: always
    ports:
      - '61617:61617'
      - '42133:42133'
      - '42155:42155'
      - '2222:22'
    volumes: 
      - duccData:/home/ducc/ducc
    networks:
      - exchange
      
volumes:
  duccDB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/duccDB"
      
  duccData:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/duccData"
      
networks:
  exchange:
    driver: bridge
